spring:
  application:
    name: api-gateway-service
  server:
    port: 9000
#  data:
#    redis:
#      host: localhost
#      port: 6379

cloud:
  gateway:
    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env